services:
  ffc-template-node:
    build:
      context: .
      target: production
    image: ffc-template-node
    container_name: ffc-template-node
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-template-node-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
  db:
    image: ankane/pgvector
    ports: ['5432:5432']
    volumes: ['./data:/var/lib/postgresql/data']
    environment: ['POSTGRES_PASSWORD=password','POSTGRES_USER=admin','POSTGRES_DB=api']
